### PR TITLE
Highlight the best card for lazy people.

### PR DESCRIPTION
**Pull request by corlettb**
This change adds a red rectangle around the best card for lazy people. This has a lot of room to be made prettier.

I've also increased the size of the "advice" text. Although I think this probably needs to be dynamic.

### CODE REVIEW

**Comment by corlettb** [comment]
Not a fan of my red rectangle? I could always reskin it for the low low price of $9.99 per side :D

**Comment by rembound** [comment]
Anything placed in the area of the card interferes with the detection process. The layout of the screen is not exactly the same on every resolution. This will result in issues on other systems.

Something like this could easily be added to the plugin system. It might be a nice feature, but we should be aware of feature creep. I like a minimal non-intrusive interface. One other thing is that the card with the most value, is not always the best card to pick. I think the player should always use their own judgement alongside the Arena Helper results.

**Comment by corlettb** [comment]
I've tried this at varying resolutions and it doesn't appear to interfere with the detection. 

Arena helper doesn't detect resolution changes mid-run btw like HDT does. Maybe we could add a quick resolution change check in there somewhere.

Obviously we could make sure the box appears outside of the detection area. Shrinking the detection area probably means we have re-scan all the cards which I can't imagine was a pleasant experience.

Although I quite often agree with hearth arena, there is usually 1-2 picks per run where we disagree. But its always good to have a that second opinion sometimes. When its an obvious choice the red box is quick way to confirm your choice is right and move on. It also a really big visual clue that arena helper has finished detection and its safe to click. On some runs I found myself clicking before arena helper had finished its detection.

I'll be honest... I not a fan of the stay on top dialog. I'd like to make further changes to move extra things to the overlay to avoid needing it on top. Like the auto deck population and probably some extra overlay text to describe the state (i.e. "Detecting arena..." etc). Probably auto close at the end of the pick as well.

I also think it might be worth adding something to the overlay to tell the user to move their mouse when they hover over a card with a popup which is covering on the of the other cards breaking the detection.

I'll happily move this to https://github.com/corlettb/HDTAHPluginHAPlugin if you want, as well as other overlay text. Maybe you could just add an option to disable the stay on top via the api (maybe I can do that already?).

I hope I'm not appearing too critical with these comments. I think arena helper is really great. Just a few rough edges :)

**Comment by corlettb** [comment]
I can see people still wanting the dialog. Like if they are running two monitors, and want to keep all the HDT stuff in the second screen and the main screen is for pure hearthstone. But I think most will want a fully functional overlay. Maybe we could make the fully functional overlay and just have an option to disable it and the dialog in the background to be dragged wherever the user wants it.

**Comment by rembound** [comment]
If it works ok with the detection, it would be a nice feature for some users. I will look into this.

**Comment by rembound** [comment]
I have been working on the card highlighting. It will be in the next version. I highlight the value of the card, rather than the card itself. This way, there won't be any detection problems. I have also added a box around the advice and tweaked the fontsize.

arena-helper-test-plugin

**Comment by corlettb** [comment]
That'll probably do the job. My red box wasn't all that pretty tbh. What did you think about making the overlay fully functional and making the stay on top window optional?

**Comment by rembound** [comment]
I think it only makes sense to move more to the overlay. HDT has a main window, but the biggest feature of HDT is the overlay.

**Comment by corlettb** [comment]
No word back on https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/1079 yet sadly. I think my ideal would require no user input what so ever for the plugin. I think the main problem would be activating it.

Do you think we could hook something that checks for the arena every 5 seconds if hearthstone is running and not in a game?

**Comment by rembound** [comment]
Every loaded plugin already gets updated every 100 ms. My plugin does nothing, when the Arena Helper window is not opened, but it could do something. I have considered that it could auto-detect the arena. I don't know if adding buttons to the overlay would be a good idea, because of the click-detection problems. Handling errors using the window works a lot better than using the overlay alone.

If detection worked flawlessly on every computer, moving everything to the overlay would be ideal. The fact is, there are corner cases, but I can make it optional. If we could auto-save the decks, like you suggested, I could add an option to use the overlay only. If detection is not flawless for a user, they could always use the default option of using the external window.

**Pull request closed without merging**
