### PR TITLE
Tierlist updated with Scholomance cards.

### PR DESCRIPTION
**Pull request by CharString**
I have updated the tierlist.

Are the CardId's and names always different from the official xml in the Lightforge api?

### CODE REVIEW

**Comment by scottismyname** [comment]
This doesn't really change much......the code gets the json data from the website and then changes it a bunch (only retaining pertinent information).

There is another pull request that automatically updates this, but it was not implemented.  Would be nice to have this working.

**Comment by CharString** [comment]
I know. I just saw it was stale. Fixed it locally (with a small bug handling 0 value cards I see) and thought I'd share it.

**Comment by rembound** [comment]
Card ids are from https://github.com/HearthSim/hsdata
Bug with 0 value cards?

**Comment by CharString** [comment]
> Bug with 0 value cards?

My conversion script didn't differentiate between "0" and "" values. I fixed it since.

**Pull request closed without merging**
